name: pytest
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Run tests via pipenv
        env:
          DJANGO_SETTINGS_MODULE: server.settings
          PYTHONPATH: ../server
        run: |
          cd job_processor
          pipenv install
          pipenv run test

