name: sonar3 part2
on:
  workflow_run:
    workflows: [sonar3]
    types: [completed]
jobs:
  sonarcloud_part2:
    name: SonarCloud part2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the new PR
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Show context
        run: |
          git remote -v
          git branch
          cat testfile
          echo "Running sonar scan with the following options:"
          echo  -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
          echo  -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
          echo  -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
          echo  -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
          echo "More debugging:"
          echo ${{ github.event.workflow_run }}
          echo ${{ github.event.workflow_run.pull_requests }}
          echo ${{ github.event.workflow_run.pull_requests.length }}
          echo ${{ github.event.workflow_run.pull_requests[0] }}
          echo ${{ github.event.workflow_run.pull_requests[0].number }}
      - name: Show some debugging
        uses: crazy-max/ghaction-dump-context@v1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
#            -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
#            -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
#            -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
