name: sonar3
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_for_sonar:
    name: SonarCloud build
    runs-on: ubuntu-latest
    steps:
      - name: Empty build step
        run: echo "Project built"

